config/routes.rb
Rails.application.routes.draw do

  resources :favourites
  resources :shows
  devise_for :users

  get 'pages/home'

  root to: "shows#index"

  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :shows
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :channel

  def self.search_shows value
    final_array = []
    channels = Channel.includes(:shows).where("name LIKE :value", value: "%#{value}%")
    shows = Show.where("name LIKE :value", value: "%#{value}%")
    
    unless channels.blank?
      channels.each do |channel|
        (channel.shows).each { |show| final_array << show }
      end
    end
    
    (final_array + shows).uniq
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites

  def is_favourite? show_id
    favourites.map(&:show_id).include?(show_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: [:show, :edit, :update]

  # GET /favourites
  # GET /favourites.json
  def index
    @favourites = Favourite.all
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = current_user.favourites.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites
  # POST /favourites.json
  def create
    @favourite = current_user.favourites.new(show_id: params[:show_id])

    respond_to do |format|
      if @favourite.save
        user_fav_show = @favourite.show
        
        ShowMailer.with(show: user_fav_show, user: @favourite.user, channel_name: user_fav_show.channel.name).reminder_show.deliver_now
        format.html { redirect_to root_path, notice: 'Favourite was successfully created.' }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1
  # PATCH/PUT /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to @favourite, notice: 'Favourite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    fav = current_user.favourites.find_by(show_id: params[:id])
    unless fav.blank?
      fav.destroy
      redirect_to root_path, notice: 'Favourite was successfully destroyed.'
    else
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favourite_params
      params.require(:favourite).permit(:show_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home;end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    unless params[:name].blank?
      @shows = Show.search_shows(params[:name])
    else
      @shows = Show.all
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show; end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit; end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    if @show.save
      redirect_to @show, notice: 'Show was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:name, :channel_id, :timing)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/favourites/_form.html.erb
<%= form_with(model: favourite, local: true) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
        <% favourite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :show_id %>
    <%= form.text_field :show_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <td><%= favourite.user_id %></td>
        <td><%= favourite.show_id %></td>
        <td><%= link_to 'Show', favourite %></td>
        <td><%= link_to 'Edit', edit_favourite_path(favourite) %></td>
        <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favourite', new_favourite_path %>

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favourite.user_id %>
</p>

<p>
  <strong>Show:</strong>
  <%= @favourite.show_id %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tvshowguide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <h1>Welcome <%= current_user.email if current_user%></h1>
    
    <% if current_user %>
      <%= link_to "Sign Out", logout_path %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to  "Sign Up", new_user_registration_path %>
    <% end %>
  
    <%= yield %>

    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome <%= current_user.email %></h1>

<% if current_user %>
  <%= link_to "Sign Out", logout_path %>
<% else %>
  <%= link_to "Sign In", new_user_session_path %>
  <%= link_to  "Sign Up", new_user_registration_path %>
<% end %> 

<%= render 'shows/shows_list' %>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.text_field :channel_id %>
  </div>

  <div class="field">
    <%= form.label :timing %>
    <%= form.time_select :timing %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shows</h1>

<%= form_tag(shows_path, method: :get) do %>
  TV Show/Channel <%= text_field_tag :name, params[:name] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Channel</th>
      <th>Timing</th>
      <th>Favourite</th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= link_to show.name, show %></td>
        <td><%= show.channel&.name %></td>
        <td><%= show.timing.strftime("%I:%M %p") %></td>
        <td>
          <% if current_user.is_favourite?(show.id) %>
            <%= link_to 'Unlike'.html_safe, favourite_path(id: show.id),method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            <%= link_to 'Like'.html_safe, favourites_path(show_id: show.id), method: :post%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @show.name %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @show.channel_id %>
</p>

<p>
  <strong>Timing:</strong>
  <%= @show.timing.strftime("%I:%M %p") %>
</p>

<%#= link_to 'Edit', edit_show_path(@show) %>
<%= link_to 'Back', shows_path %>